---
services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  # Test building Dockerfile.
  - docker build -t docker-ansible .

  # Test running the container.
  - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible /usr/lib/systemd/systemd
